Documented the `module = "dependency:module"` syntax and known command annotations
wasmerio/docs.wasmer.io pull request #47
Opened 2023-10-06 07:25 UTC by Michael-F-Bryan

2023-10-06 09:22 UTC, dynamite-bud requested changes

2023-10-06 09:22 UTC, dynamite-bud commented on pages/registry/manifest.mdx
> +The manifest file contains 5 top-level sections.
Can we name the four sections in a list first

2023-10-13 02:30 UTC, Michael-F-Bryan commented on pages/registry/manifest.mdx
Done.

2023-10-13 08:42 UTC, dynamite-bud approved these changes
LGTM

2023-10-13 08:43 UTC, merged